
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is HotelesGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using serin_viaticosRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace serin_viaticosRules.Gateways
{

    public partial class HotelesGateway : BaseGateway<HotelesObject, HotelesObjectList>, IGenericGateway
    {

        #region "Singleton"

        static HotelesGateway _instance;

        private HotelesGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static HotelesGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new HotelesGateway();
                else {
                    HotelesGateway inst = HttpContext.Current.Items["serin_viaticosRules.HotelesGatewaySingleton"] as HotelesGateway;
                    if (inst == null) {
                        inst = new HotelesGateway();
                        HttpContext.Current.Items.Add("serin_viaticosRules.HotelesGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "Hoteles"; }
        }

        protected override string RuleName
        {
            get {return typeof(HotelesGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, HotelesObject entity)
        {
            
            IMappeableHotelesObject Hoteles = (IMappeableHotelesObject)entity;
            Hoteles.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1),
reader.GetInt32(2),
(reader.IsDBNull(3)) ? "" : reader.GetString(3),
(reader.IsDBNull(4)) ? "" : reader.GetString(4),
reader.GetString(5));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(HotelesObject entity)
        {

            IMappeableHotelesObject Hoteles = (IMappeableHotelesObject)entity;
            return Hoteles.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(HotelesObject entity)
        {

            IMappeableHotelesObject Hoteles = (IMappeableHotelesObject)entity;
            return Hoteles.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(HotelesObject entity)
        {

            IMappeableHotelesObject Hoteles = (IMappeableHotelesObject)entity;
            return Hoteles.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(HotelesObject row, object[] parameters)
        {
            ((IMappeableHotelesObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        /// <summary>
        /// Get a HotelesObject by execute a SQL Query Text
        /// </summary>
        public HotelesObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a HotelesObjectList by execute a SQL Query Text
        /// </summary>
        public HotelesObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a HotelesObject by calling a Stored Procedure
        /// </summary>
        public HotelesObject GetOne(System.Int32 IdHotel)
        {
            return base.GetOne(new HotelesObject(IdHotel));
        }


        // GetBy Objects and Params
            


        

        

        /// <summary>
        /// Delete Hoteles
        /// </summary>
        public void Delete(System.Int32 IdHotel)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "Hoteles_Delete", IdHotel);
        }

        /// <summary>
        /// Delete Hoteles
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdHotel)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "Hoteles_Delete", IdHotel);
        }

            

        


        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








