
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is ItinerarioGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using serin_viaticosRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace serin_viaticosRules.Gateways
{

    public partial class ItinerarioGateway : BaseGateway<ItinerarioObject, ItinerarioObjectList>, IGenericGateway
    {

        #region "Singleton"

        static ItinerarioGateway _instance;

        private ItinerarioGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static ItinerarioGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new ItinerarioGateway();
                else {
                    ItinerarioGateway inst = HttpContext.Current.Items["serin_viaticosRules.ItinerarioGatewaySingleton"] as ItinerarioGateway;
                    if (inst == null) {
                        inst = new ItinerarioGateway();
                        HttpContext.Current.Items.Add("serin_viaticosRules.ItinerarioGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "Itinerario"; }
        }

        protected override string RuleName
        {
            get {return typeof(ItinerarioGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, ItinerarioObject entity)
        {
            
            IMappeableItinerarioObject Itinerario = (IMappeableItinerarioObject)entity;
            Itinerario.HydrateFields(
            reader.GetInt32(0),
reader.GetDateTime(1),
reader.GetBoolean(2));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(ItinerarioObject entity)
        {

            IMappeableItinerarioObject Itinerario = (IMappeableItinerarioObject)entity;
            return Itinerario.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(ItinerarioObject entity)
        {

            IMappeableItinerarioObject Itinerario = (IMappeableItinerarioObject)entity;
            return Itinerario.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(ItinerarioObject entity)
        {

            IMappeableItinerarioObject Itinerario = (IMappeableItinerarioObject)entity;
            return Itinerario.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(ItinerarioObject row, object[] parameters)
        {
            ((IMappeableItinerarioObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        /// <summary>
        /// Get a ItinerarioObject by execute a SQL Query Text
        /// </summary>
        public ItinerarioObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a ItinerarioObjectList by execute a SQL Query Text
        /// </summary>
        public ItinerarioObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a ItinerarioObject by calling a Stored Procedure
        /// </summary>
        public ItinerarioObject GetOne(System.Int32 IdItinerario)
        {
            return base.GetOne(new ItinerarioObject(IdItinerario));
        }


        // GetBy Objects and Params
            


        

        

        /// <summary>
        /// Delete Itinerario
        /// </summary>
        public void Delete(System.Int32 IdItinerario)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "Itinerario_Delete", IdItinerario);
        }

        /// <summary>
        /// Delete Itinerario
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdItinerario)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "Itinerario_Delete", IdItinerario);
        }

            

        


        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








