
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is UbicacionesGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using serin_viaticosRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace serin_viaticosRules.Gateways
{

    public partial class UbicacionesGateway : BaseGateway<UbicacionesObject, UbicacionesObjectList>, IGenericGateway
    {

        #region "Singleton"

        static UbicacionesGateway _instance;

        private UbicacionesGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static UbicacionesGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new UbicacionesGateway();
                else {
                    UbicacionesGateway inst = HttpContext.Current.Items["serin_viaticosRules.UbicacionesGatewaySingleton"] as UbicacionesGateway;
                    if (inst == null) {
                        inst = new UbicacionesGateway();
                        HttpContext.Current.Items.Add("serin_viaticosRules.UbicacionesGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "Ubicaciones"; }
        }

        protected override string RuleName
        {
            get {return typeof(UbicacionesGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, UbicacionesObject entity)
        {
            
            IMappeableUbicacionesObject Ubicaciones = (IMappeableUbicacionesObject)entity;
            Ubicaciones.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1),
(reader.IsDBNull(2)) ? new System.Nullable<System.Int64>() : reader.GetInt64(2),
(reader.IsDBNull(3)) ? new System.Nullable<System.Int64>() : reader.GetInt64(3));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(UbicacionesObject entity)
        {

            IMappeableUbicacionesObject Ubicaciones = (IMappeableUbicacionesObject)entity;
            return Ubicaciones.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(UbicacionesObject entity)
        {

            IMappeableUbicacionesObject Ubicaciones = (IMappeableUbicacionesObject)entity;
            return Ubicaciones.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(UbicacionesObject entity)
        {

            IMappeableUbicacionesObject Ubicaciones = (IMappeableUbicacionesObject)entity;
            return Ubicaciones.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(UbicacionesObject row, object[] parameters)
        {
            ((IMappeableUbicacionesObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        /// <summary>
        /// Get a UbicacionesObject by execute a SQL Query Text
        /// </summary>
        public UbicacionesObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a UbicacionesObjectList by execute a SQL Query Text
        /// </summary>
        public UbicacionesObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a UbicacionesObject by calling a Stored Procedure
        /// </summary>
        public UbicacionesObject GetOne(System.Int32 IdUbicacion)
        {
            return base.GetOne(new UbicacionesObject(IdUbicacion));
        }


        // GetBy Objects and Params
            


        

        

        /// <summary>
        /// Delete Ubicaciones
        /// </summary>
        public void Delete(System.Int32 IdUbicacion)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "Ubicaciones_Delete", IdUbicacion);
        }

        /// <summary>
        /// Delete Ubicaciones
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdUbicacion)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "Ubicaciones_Delete", IdUbicacion);
        }

            

        


        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








