
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is UsuariosDependenciaGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using serin_viaticosRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace serin_viaticosRules.Gateways
{

    public partial class UsuariosDependenciaGateway : BaseGateway<UsuariosDependenciaObject, UsuariosDependenciaObjectList>, IGenericGateway
    {

        #region "Singleton"

        static UsuariosDependenciaGateway _instance;

        private UsuariosDependenciaGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static UsuariosDependenciaGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new UsuariosDependenciaGateway();
                else {
                    UsuariosDependenciaGateway inst = HttpContext.Current.Items["serin_viaticosRules.UsuariosDependenciaGatewaySingleton"] as UsuariosDependenciaGateway;
                    if (inst == null) {
                        inst = new UsuariosDependenciaGateway();
                        HttpContext.Current.Items.Add("serin_viaticosRules.UsuariosDependenciaGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "UsuariosDependencia"; }
        }

        protected override string RuleName
        {
            get {return typeof(UsuariosDependenciaGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, UsuariosDependenciaObject entity)
        {
            
            IMappeableUsuariosDependenciaObject UsuariosDependencia = (IMappeableUsuariosDependenciaObject)entity;
            UsuariosDependencia.HydrateFields(
            reader.GetInt32(0),
reader.GetInt32(1),
reader.GetInt32(2));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(UsuariosDependenciaObject entity)
        {

            IMappeableUsuariosDependenciaObject UsuariosDependencia = (IMappeableUsuariosDependenciaObject)entity;
            return UsuariosDependencia.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(UsuariosDependenciaObject entity)
        {

            IMappeableUsuariosDependenciaObject UsuariosDependencia = (IMappeableUsuariosDependenciaObject)entity;
            return UsuariosDependencia.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(UsuariosDependenciaObject entity)
        {

            IMappeableUsuariosDependenciaObject UsuariosDependencia = (IMappeableUsuariosDependenciaObject)entity;
            return UsuariosDependencia.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(UsuariosDependenciaObject row, object[] parameters)
        {
            ((IMappeableUsuariosDependenciaObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        /// <summary>
        /// Get a UsuariosDependenciaObject by execute a SQL Query Text
        /// </summary>
        public UsuariosDependenciaObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a UsuariosDependenciaObjectList by execute a SQL Query Text
        /// </summary>
        public UsuariosDependenciaObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a UsuariosDependenciaObject by calling a Stored Procedure
        /// </summary>
        public UsuariosDependenciaObject GetOne(System.Int32 IdDependenciaUsuario)
        {
            return base.GetOne(new UsuariosDependenciaObject(IdDependenciaUsuario));
        }


        // GetBy Objects and Params
            


        

        

        /// <summary>
        /// Delete UsuariosDependencia
        /// </summary>
        public void Delete(System.Int32 IdDependenciaUsuario)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "UsuariosDependencia_Delete", IdDependenciaUsuario);
        }

        /// <summary>
        /// Delete UsuariosDependencia
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdDependenciaUsuario)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "UsuariosDependencia_Delete", IdDependenciaUsuario);
        }

            

        


        //Database Queries 
        
            

        /// <summary>
        /// 
        /// </summary>
        public UsuariosDependenciaObject GetByUsuarioPadreHijo(System.Int32 IdUsuarioPadre, System.Int32 IdUsuarioHijo) {
            
            return base.GetObjectByAnyStoredProcedure(StoredProceduresPrefix() + "UsuariosDependencia_GetByUsuarioPadreHijo" , IdUsuarioPadre, IdUsuarioHijo);
            
        }

        
        /// <summary>
        /// 
        /// </summary>
        public UsuariosDependenciaObject GetByUsuarioPadreHijo(DbTransaction transaction , System.Int32 IdUsuarioPadre, System.Int32 IdUsuarioHijo) {
            
            return base.GetObjectByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "UsuariosDependencia_GetByUsuarioPadreHijo" , IdUsuarioPadre, IdUsuarioHijo);
            
        }


        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








