
        
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is CategoriasGastoObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace serin_viaticosRules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class CategoriasGastoObject : BaseObject, IMappeableCategoriasGastoObject, IUniqueIdentifiable, IEquatable<CategoriasGastoObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public CategoriasGastoObject(): base()
        {

			_IdCategoriaGasto =  ValuesGenerator.GetInt32;

        }

        /// <summary>
        /// 
        /// </summary>
        public CategoriasGastoObject(
			System.Int32 IdCategoriaGasto): base()
        {

			_IdCategoriaGasto = IdCategoriaGasto;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public CategoriasGastoObject(
			System.Int32 IdCategoriaGasto,
			System.String Nombre,
			System.Boolean Activo,
			System.String EmailNotificacion): base()
        {

			_IdCategoriaGasto = IdCategoriaGasto;
			_Nombre = Nombre;
			_Activo = Activo;
			_EmailNotificacion = EmailNotificacion;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _IdCategoriaGasto;
/// <summary>
/// 
/// </summary>
protected System.String _Nombre;
/// <summary>
/// 
/// </summary>
protected System.Boolean _Activo;
/// <summary>
/// 
/// </summary>
protected System.String _EmailNotificacion;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdCategoriaGasto
        {
            get
            {
                return _IdCategoriaGasto;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            
            set
            {
                base.PropertyModified();
                _Nombre = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            
            set
            {
                base.PropertyModified();
                _Activo = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String EmailNotificacion
        {
            get
            {
                return _EmailNotificacion;
            }
            
            set
            {
                base.PropertyModified();
                _EmailNotificacion = value;
                
            }
            
        }
        
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            CategoriasGastoObject newObject;
            CategoriasGastoObject newOriginalValue;

            newObject = (CategoriasGastoObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (CategoriasGastoObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new CategoriasGastoObject OriginalValue()
        {
            return (CategoriasGastoObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableCategoriasGastoObject.HydrateFields(
			System.Int32 IdCategoriaGasto,
			System.String Nombre,
			System.Boolean Activo,
			System.String EmailNotificacion)
        {
        _IdCategoriaGasto = IdCategoriaGasto;
_Nombre = Nombre;
_Activo = Activo;
_EmailNotificacion = EmailNotificacion;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableCategoriasGastoObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[4];
            _myArray[0] = _IdCategoriaGasto;
_myArray[1] = _Nombre;
_myArray[2] = _Activo;
_myArray[3] = _EmailNotificacion;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableCategoriasGastoObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[4];
            _myArray[0] = _IdCategoriaGasto;
_myArray[1] = _Nombre;
_myArray[2] = _Activo;
_myArray[3] = _EmailNotificacion;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableCategoriasGastoObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _IdCategoriaGasto;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableCategoriasGastoObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            _IdCategoriaGasto = (System.Int32) parameters[0];

        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            CategoriasGastoObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.IdCategoriaGasto};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(CategoriasGastoObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableCategoriasGastoObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 IdCategoriaGasto, 
			System.String Nombre, 
			System.Boolean Activo, 
			System.String EmailNotificacion);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class CategoriasGastoObjectList : ObjectList<CategoriasGastoObject>
    {
    }
}

namespace serin_viaticosRules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class CategoriasGastoObjectListView
        : ObjectListView<Objects.CategoriasGastoObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public CategoriasGastoObjectListView(Objects.CategoriasGastoObjectList list): base(list)
        {
        }
    }
}


