
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is PerfilesUsuariosObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace serin_viaticosRules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class PerfilesUsuariosObject : BaseObject, IMappeablePerfilesUsuariosObject, IUniqueIdentifiable, IEquatable<PerfilesUsuariosObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public PerfilesUsuariosObject(): base()
        {

			_IdUsuario =  ValuesGenerator.GetInt32;

        }

        /// <summary>
        /// 
        /// </summary>
        public PerfilesUsuariosObject(
			System.Int32 IdUsuarioPerfil): base()
        {

			_IdUsuarioPerfil = IdUsuarioPerfil;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public PerfilesUsuariosObject(
			System.Int32 IdUsuarioPerfil,
			System.Int32 IdUsuario,
			System.Int32 IdPerfil): base()
        {

			_IdUsuarioPerfil = IdUsuarioPerfil;
			_IdUsuario = IdUsuario;
			_IdPerfil = IdPerfil;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _IdUsuarioPerfil;
/// <summary>
/// 
/// </summary>
protected System.Int32 _IdUsuario;
/// <summary>
/// 
/// </summary>
protected System.Int32 _IdPerfil;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdUsuarioPerfil
        {
            get
            {
                return _IdUsuarioPerfil;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            
            set
            {
                base.PropertyModified();
                _IdUsuario = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdPerfil
        {
            get
            {
                return _IdPerfil;
            }
            
            set
            {
                base.PropertyModified();
                _IdPerfil = value;
                
            }
            
        }
        
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            PerfilesUsuariosObject newObject;
            PerfilesUsuariosObject newOriginalValue;

            newObject = (PerfilesUsuariosObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (PerfilesUsuariosObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new PerfilesUsuariosObject OriginalValue()
        {
            return (PerfilesUsuariosObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeablePerfilesUsuariosObject.HydrateFields(
			System.Int32 IdUsuarioPerfil,
			System.Int32 IdUsuario,
			System.Int32 IdPerfil)
        {
        _IdUsuarioPerfil = IdUsuarioPerfil;
_IdUsuario = IdUsuario;
_IdPerfil = IdPerfil;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeablePerfilesUsuariosObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[3];
            _myArray[0] = _IdUsuarioPerfil;
_myArray[1] = _IdUsuario;
_myArray[2] = _IdPerfil;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeablePerfilesUsuariosObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[3];
            _myArray[0] = _IdUsuarioPerfil;
_myArray[1] = _IdUsuario;
_myArray[2] = _IdPerfil;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeablePerfilesUsuariosObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _IdUsuarioPerfil;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeablePerfilesUsuariosObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            _IdUsuarioPerfil = (System.Int32) parameters[0];

        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            PerfilesUsuariosObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.IdUsuarioPerfil};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(PerfilesUsuariosObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeablePerfilesUsuariosObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 IdUsuarioPerfil, 
			System.Int32 IdUsuario, 
			System.Int32 IdPerfil);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class PerfilesUsuariosObjectList : ObjectList<PerfilesUsuariosObject>
    {
    }
}

namespace serin_viaticosRules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class PerfilesUsuariosObjectListView
        : ObjectListView<Objects.PerfilesUsuariosObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public PerfilesUsuariosObjectListView(Objects.PerfilesUsuariosObjectList list): base(list)
        {
        }
    }
}


