
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is ReservasAereosObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace serin_viaticosRules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ReservasAereosObject : BaseObject, IMappeableReservasAereosObject, IUniqueIdentifiable, IEquatable<ReservasAereosObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public ReservasAereosObject(): base()
        {


        }

        /// <summary>
        /// 
        /// </summary>
        public ReservasAereosObject(
			System.Int32 IdReservaAereo): base()
        {

			_IdReservaAereo = IdReservaAereo;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public ReservasAereosObject(
			System.Int32 IdReservaAereo,
			System.Int32 IdOrigen,
			System.Int32 IdDestino,
			System.Int32 CantPasajeros,
			System.DateTime FechaViaje,
			System.Boolean IdaVuelta,
			System.Nullable<System.Decimal> Precio,
			System.Nullable<System.DateTime> FechaRegreso): base()
        {

			_IdReservaAereo = IdReservaAereo;
			_IdOrigen = IdOrigen;
			_IdDestino = IdDestino;
			_CantPasajeros = CantPasajeros;
			_FechaViaje = FechaViaje;
			_IdaVuelta = IdaVuelta;
			_Precio = Precio;
			_FechaRegreso = FechaRegreso;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _IdReservaAereo;
/// <summary>
/// 
/// </summary>
protected System.Int32 _IdOrigen;
/// <summary>
/// 
/// </summary>
protected System.Int32 _IdDestino;
/// <summary>
/// 
/// </summary>
protected System.Int32 _CantPasajeros;
/// <summary>
/// 
/// </summary>
protected System.DateTime _FechaViaje;
/// <summary>
/// 
/// </summary>
protected System.Boolean _IdaVuelta;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Decimal> _Precio;
/// <summary>
///
/// </summary>
protected System.Nullable<System.DateTime> _FechaRegreso;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdReservaAereo
        {
            get
            {
                return _IdReservaAereo;
            }
            
            set
            {
                base.PropertyModified();
                _IdReservaAereo = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdOrigen
        {
            get
            {
                return _IdOrigen;
            }
            
            set
            {
                base.PropertyModified();
                _IdOrigen = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdDestino
        {
            get
            {
                return _IdDestino;
            }
            
            set
            {
                base.PropertyModified();
                _IdDestino = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 CantPasajeros
        {
            get
            {
                return _CantPasajeros;
            }
            
            set
            {
                base.PropertyModified();
                _CantPasajeros = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.DateTime FechaViaje
        {
            get
            {
                return _FechaViaje;
            }
            
            set
            {
                base.PropertyModified();
                _FechaViaje = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Boolean IdaVuelta
        {
            get
            {
                return _IdaVuelta;
            }
            
            set
            {
                base.PropertyModified();
                _IdaVuelta = value;
                
            }
            
        }
        
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Decimal> Precio
        {
            get
            {
                return _Precio;
            }
            
            set
            {
                base.PropertyModified();
                _Precio = value;                
                
            }
            
        }
                
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaRegreso
        {
            get
            {
                return _FechaRegreso;
            }
            
            set
            {
                base.PropertyModified();
                _FechaRegreso = value;                
                
            }
            
        }
                
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            ReservasAereosObject newObject;
            ReservasAereosObject newOriginalValue;

            newObject = (ReservasAereosObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (ReservasAereosObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new ReservasAereosObject OriginalValue()
        {
            return (ReservasAereosObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableReservasAereosObject.HydrateFields(
			System.Int32 IdReservaAereo,
			System.Int32 IdOrigen,
			System.Int32 IdDestino,
			System.Int32 CantPasajeros,
			System.DateTime FechaViaje,
			System.Boolean IdaVuelta,
			System.Nullable<System.Decimal> Precio,
			System.Nullable<System.DateTime> FechaRegreso)
        {
        _IdReservaAereo = IdReservaAereo;
_IdOrigen = IdOrigen;
_IdDestino = IdDestino;
_CantPasajeros = CantPasajeros;
_FechaViaje = FechaViaje;
_IdaVuelta = IdaVuelta;
_Precio = Precio;
_FechaRegreso = FechaRegreso;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableReservasAereosObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[8];
            _myArray[0] = _IdReservaAereo;
_myArray[1] = _IdOrigen;
_myArray[2] = _IdDestino;
_myArray[3] = _CantPasajeros;
_myArray[4] = _FechaViaje;
_myArray[5] = _IdaVuelta;
if (_Precio.HasValue) _myArray[6] = _Precio.Value;
if (_FechaRegreso.HasValue) _myArray[7] = _FechaRegreso.Value;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableReservasAereosObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[9];
            _myArray[0] = _IdReservaAereo;
_myArray[1] = _IdOrigen;
_myArray[2] = _IdDestino;
_myArray[3] = _CantPasajeros;
_myArray[4] = _FechaViaje;
_myArray[5] = _IdaVuelta;
if (_Precio.HasValue) _myArray[6] = _Precio.Value;
if (_FechaRegreso.HasValue) _myArray[7] = _FechaRegreso.Value;
_myArray[8] = this.OriginalValue()._IdReservaAereo;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableReservasAereosObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _IdReservaAereo;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableReservasAereosObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            
        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            ReservasAereosObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.IdReservaAereo};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(ReservasAereosObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableReservasAereosObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 IdReservaAereo, 
			System.Int32 IdOrigen, 
			System.Int32 IdDestino, 
			System.Int32 CantPasajeros, 
			System.DateTime FechaViaje, 
			System.Boolean IdaVuelta, 
			System.Nullable<System.Decimal> Precio, 
			System.Nullable<System.DateTime> FechaRegreso);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class ReservasAereosObjectList : ObjectList<ReservasAereosObject>
    {
    }
}

namespace serin_viaticosRules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ReservasAereosObjectListView
        : ObjectListView<Objects.ReservasAereosObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public ReservasAereosObjectListView(Objects.ReservasAereosObjectList list): base(list)
        {
        }
    }
}


