
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is SolicitudesUsuariosObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace serin_viaticosRules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class SolicitudesUsuariosObject : BaseObject, IMappeableSolicitudesUsuariosObject, IUniqueIdentifiable, IEquatable<SolicitudesUsuariosObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public SolicitudesUsuariosObject(): base()
        {


        }

        /// <summary>
        /// 
        /// </summary>
        public SolicitudesUsuariosObject(
			System.Int32 IdSolicitudUsuario): base()
        {

			_IdSolicitudUsuario = IdSolicitudUsuario;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public SolicitudesUsuariosObject(
			System.Int32 IdSolicitudUsuario,
			System.Int32 IdSolicitud,
			System.Int32 IdUsuario,
			System.Nullable<System.Decimal> MontoAnticipo): base()
        {

			_IdSolicitudUsuario = IdSolicitudUsuario;
			_IdSolicitud = IdSolicitud;
			_IdUsuario = IdUsuario;
			_MontoAnticipo = MontoAnticipo;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _IdSolicitudUsuario;
/// <summary>
/// 
/// </summary>
protected System.Int32 _IdSolicitud;
/// <summary>
/// 
/// </summary>
protected System.Int32 _IdUsuario;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Decimal> _MontoAnticipo;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdSolicitudUsuario
        {
            get
            {
                return _IdSolicitudUsuario;
            }
            
            set
            {
                base.PropertyModified();
                _IdSolicitudUsuario = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdSolicitud
        {
            get
            {
                return _IdSolicitud;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            
            set
            {
                base.PropertyModified();
                _IdUsuario = value;
                
            }
            
        }
        
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Decimal> MontoAnticipo
        {
            get
            {
                return _MontoAnticipo;
            }
            
            set
            {
                base.PropertyModified();
                _MontoAnticipo = value;                
                
            }
            
        }
                
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            SolicitudesUsuariosObject newObject;
            SolicitudesUsuariosObject newOriginalValue;

            newObject = (SolicitudesUsuariosObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (SolicitudesUsuariosObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new SolicitudesUsuariosObject OriginalValue()
        {
            return (SolicitudesUsuariosObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableSolicitudesUsuariosObject.HydrateFields(
			System.Int32 IdSolicitudUsuario,
			System.Int32 IdSolicitud,
			System.Int32 IdUsuario,
			System.Nullable<System.Decimal> MontoAnticipo)
        {
        _IdSolicitudUsuario = IdSolicitudUsuario;
_IdSolicitud = IdSolicitud;
_IdUsuario = IdUsuario;
_MontoAnticipo = MontoAnticipo;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableSolicitudesUsuariosObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[4];
            _myArray[0] = _IdSolicitudUsuario;
_myArray[1] = _IdSolicitud;
_myArray[2] = _IdUsuario;
if (_MontoAnticipo.HasValue) _myArray[3] = _MontoAnticipo.Value;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableSolicitudesUsuariosObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[5];
            _myArray[0] = _IdSolicitudUsuario;
_myArray[1] = _IdSolicitud;
_myArray[2] = _IdUsuario;
if (_MontoAnticipo.HasValue) _myArray[3] = _MontoAnticipo.Value;
_myArray[4] = this.OriginalValue()._IdSolicitudUsuario;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableSolicitudesUsuariosObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _IdSolicitudUsuario;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableSolicitudesUsuariosObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            _IdSolicitud = (System.Int32) parameters[1];

        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            SolicitudesUsuariosObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.IdSolicitudUsuario};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(SolicitudesUsuariosObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableSolicitudesUsuariosObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 IdSolicitudUsuario, 
			System.Int32 IdSolicitud, 
			System.Int32 IdUsuario, 
			System.Nullable<System.Decimal> MontoAnticipo);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class SolicitudesUsuariosObjectList : ObjectList<SolicitudesUsuariosObject>
    {
    }
}

namespace serin_viaticosRules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class SolicitudesUsuariosObjectListView
        : ObjectListView<Objects.SolicitudesUsuariosObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public SolicitudesUsuariosObjectListView(Objects.SolicitudesUsuariosObjectList list): base(list)
        {
        }
    }
}


