
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is SolicitudesDetalleObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace serin_viaticosRules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class SolicitudesDetalleObject : BaseObject, IMappeableSolicitudesDetalleObject, IUniqueIdentifiable, IEquatable<SolicitudesDetalleObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public SolicitudesDetalleObject(): base()
        {

			_IdSolicitudDetalle =  ValuesGenerator.GetInt32;

        }

        /// <summary>
        /// 
        /// </summary>
        public SolicitudesDetalleObject(
			System.Int32 IdSolicitudDetalle): base()
        {

			_IdSolicitudDetalle = IdSolicitudDetalle;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public SolicitudesDetalleObject(
			System.Int32 IdSolicitudDetalle,
			System.Int32 IdSolicitud,
			System.Int32 IdSolicitudCategoria,
			System.Nullable<System.Int32> IdReservaAereo,
			System.Nullable<System.Int32> IdResevaHotel,
			System.Nullable<System.Int32> IdItinerario,
			System.Nullable<System.Int32> IdReservaAlquilerAuto,
			System.String Observaciones): base()
        {

			_IdSolicitudDetalle = IdSolicitudDetalle;
			_IdSolicitud = IdSolicitud;
			_IdSolicitudCategoria = IdSolicitudCategoria;
			_IdReservaAereo = IdReservaAereo;
			_IdResevaHotel = IdResevaHotel;
			_IdItinerario = IdItinerario;
			_IdReservaAlquilerAuto = IdReservaAlquilerAuto;
			_Observaciones = Observaciones;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _IdSolicitudDetalle;
/// <summary>
/// 
/// </summary>
protected System.Int32 _IdSolicitud;
/// <summary>
/// 
/// </summary>
protected System.Int32 _IdSolicitudCategoria;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _IdReservaAereo;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _IdResevaHotel;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _IdItinerario;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _IdReservaAlquilerAuto;
/// <summary>
/// 
/// </summary>
protected System.String _Observaciones;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdSolicitudDetalle
        {
            get
            {
                return _IdSolicitudDetalle;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdSolicitud
        {
            get
            {
                return _IdSolicitud;
            }
            
            set
            {
                base.PropertyModified();
                _IdSolicitud = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdSolicitudCategoria
        {
            get
            {
                return _IdSolicitudCategoria;
            }
            
            set
            {
                base.PropertyModified();
                _IdSolicitudCategoria = value;
                
            }
            
        }
        
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> IdReservaAereo
        {
            get
            {
                return _IdReservaAereo;
            }
            
            set
            {
                base.PropertyModified();
                _IdReservaAereo = value;                
                
            }
            
        }
                
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> IdResevaHotel
        {
            get
            {
                return _IdResevaHotel;
            }
            
            set
            {
                base.PropertyModified();
                _IdResevaHotel = value;                
                
            }
            
        }
                
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> IdItinerario
        {
            get
            {
                return _IdItinerario;
            }
            
            set
            {
                base.PropertyModified();
                _IdItinerario = value;                
                
            }
            
        }
                
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> IdReservaAlquilerAuto
        {
            get
            {
                return _IdReservaAlquilerAuto;
            }
            
            set
            {
                base.PropertyModified();
                _IdReservaAlquilerAuto = value;                
                
            }
            
        }
                
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Observaciones
        {
            get
            {
                return _Observaciones;
            }
            
            set
            {
                base.PropertyModified();
                _Observaciones = value;
                
            }
            
        }
        
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            SolicitudesDetalleObject newObject;
            SolicitudesDetalleObject newOriginalValue;

            newObject = (SolicitudesDetalleObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (SolicitudesDetalleObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new SolicitudesDetalleObject OriginalValue()
        {
            return (SolicitudesDetalleObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableSolicitudesDetalleObject.HydrateFields(
			System.Int32 IdSolicitudDetalle,
			System.Int32 IdSolicitud,
			System.Int32 IdSolicitudCategoria,
			System.Nullable<System.Int32> IdReservaAereo,
			System.Nullable<System.Int32> IdResevaHotel,
			System.Nullable<System.Int32> IdItinerario,
			System.Nullable<System.Int32> IdReservaAlquilerAuto,
			System.String Observaciones)
        {
        _IdSolicitudDetalle = IdSolicitudDetalle;
_IdSolicitud = IdSolicitud;
_IdSolicitudCategoria = IdSolicitudCategoria;
_IdReservaAereo = IdReservaAereo;
_IdResevaHotel = IdResevaHotel;
_IdItinerario = IdItinerario;
_IdReservaAlquilerAuto = IdReservaAlquilerAuto;
_Observaciones = Observaciones;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableSolicitudesDetalleObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[8];
            _myArray[0] = _IdSolicitudDetalle;
_myArray[1] = _IdSolicitud;
_myArray[2] = _IdSolicitudCategoria;
if (_IdReservaAereo.HasValue) _myArray[3] = _IdReservaAereo.Value;
if (_IdResevaHotel.HasValue) _myArray[4] = _IdResevaHotel.Value;
if (_IdItinerario.HasValue) _myArray[5] = _IdItinerario.Value;
if (_IdReservaAlquilerAuto.HasValue) _myArray[6] = _IdReservaAlquilerAuto.Value;
if (!System.String.IsNullOrEmpty(_Observaciones)) _myArray[7] = _Observaciones;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableSolicitudesDetalleObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[8];
            _myArray[0] = _IdSolicitudDetalle;
_myArray[1] = _IdSolicitud;
_myArray[2] = _IdSolicitudCategoria;
if (_IdReservaAereo.HasValue) _myArray[3] = _IdReservaAereo.Value;
if (_IdResevaHotel.HasValue) _myArray[4] = _IdResevaHotel.Value;
if (_IdItinerario.HasValue) _myArray[5] = _IdItinerario.Value;
if (_IdReservaAlquilerAuto.HasValue) _myArray[6] = _IdReservaAlquilerAuto.Value;
if (!System.String.IsNullOrEmpty(_Observaciones)) _myArray[7] = _Observaciones;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableSolicitudesDetalleObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _IdSolicitudDetalle;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableSolicitudesDetalleObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            _IdSolicitudDetalle = (System.Int32) parameters[0];

        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            SolicitudesDetalleObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.IdSolicitudDetalle};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(SolicitudesDetalleObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableSolicitudesDetalleObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 IdSolicitudDetalle, 
			System.Int32 IdSolicitud, 
			System.Int32 IdSolicitudCategoria, 
			System.Nullable<System.Int32> IdReservaAereo, 
			System.Nullable<System.Int32> IdResevaHotel, 
			System.Nullable<System.Int32> IdItinerario, 
			System.Nullable<System.Int32> IdReservaAlquilerAuto, 
			System.String Observaciones);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class SolicitudesDetalleObjectList : ObjectList<SolicitudesDetalleObject>
    {
    }
}

namespace serin_viaticosRules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class SolicitudesDetalleObjectListView
        : ObjectListView<Objects.SolicitudesDetalleObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public SolicitudesDetalleObjectListView(Objects.SolicitudesDetalleObjectList list): base(list)
        {
        }
    }
}


