
        
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 27/09/2022 - 8:10
// This is a partial class file. The other one is CategoriasGastoGateway.Auto.cs
// You can edit this file as your wish.
//------------------------------------------------------------------------------

using serin_viaticosRules.Objects;
using Cooperator.Framework.Core;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using System.Data.Common;
using System.Reflection;
using System;

namespace serin_viaticosRules.Gateways
{

    /// <summary>
    /// Gateway between CategoriasGastoObject class and CategoriasGasto table.
    /// This class provide CRUD methods for CategoriasGasto table.
    /// </summary>
    public partial class CategoriasGastoGateway
    {
        // /// <summary>
        // /// Enables GetObjectBySQLText and GetObjectListBySQLText methods.
        // /// </summary>
        //protected override bool SQLQueriesEnabled()
        //{
        //    return true;
        //}


        // /// <summary>
        // /// Checks for security ritghs
        // /// </summary>
        //protected override bool CheckForSecurityRights(SecurityRights action, CategoriasGastoObjectList ObjectListOrEntityList)
        //{
        //    switch (action)
        //    {
        //        case SecurityRights.Read:
        //            return true;
        //        case SecurityRights.Insert:
        //            return true;
        //        case SecurityRights.Update:
        //            return true;
        //        case SecurityRights.Delete:
        //            return true;
        //    }
        //    return false;
        //}

    }

}



