
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is ReservasAlquilerAutoMapper.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using serin_viaticosRules.Entities;
using serin_viaticosRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data.Common;
using System.Reflection;
using System.Web;
using System.Data;

namespace serin_viaticosRules.Mappers
{

    
    /// <summary>
    /// 
    /// </summary>
    public partial class ReservasAlquilerAutoMapper : BaseGateway<ReservasAlquilerAuto, ReservasAlquilerAutoList>, IGenericGateway
    {


        #region "Singleton"

        static ReservasAlquilerAutoMapper _instance;

        private ReservasAlquilerAutoMapper()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static ReservasAlquilerAutoMapper Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new ReservasAlquilerAutoMapper();
                else {
                    ReservasAlquilerAutoMapper inst = HttpContext.Current.Items["serin_viaticosRules.ReservasAlquilerAutoMapperSingleton"] as ReservasAlquilerAutoMapper;
                    if (inst == null) {
                        inst = new ReservasAlquilerAutoMapper();
                        HttpContext.Current.Items.Add("serin_viaticosRules.ReservasAlquilerAutoMapperSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"IdReservaAlquilerAuto"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(ReservasAlquilerAuto);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "ReservasAlquilerAuto"; }
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string RuleName
        {
            get {return typeof(ReservasAlquilerAutoMapper).FullName;}
        }


        

        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, ReservasAlquilerAuto entity)
        {
            
            IMappeableReservasAlquilerAutoObject ReservasAlquilerAuto = (IMappeableReservasAlquilerAutoObject)entity;
            ReservasAlquilerAuto.HydrateFields(
            reader.GetInt32(0),
reader.GetInt32(1),
reader.GetInt32(2),
reader.GetString(3),
reader.GetString(4),
reader.GetDateTime(5),
reader.GetDateTime(6),
(reader.IsDBNull(7)) ? new System.Nullable<System.Decimal>() : reader.GetDecimal(7));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForInsert(ReservasAlquilerAuto entity)
        {

            IMappeableReservasAlquilerAutoObject ReservasAlquilerAuto = (IMappeableReservasAlquilerAutoObject)entity;
            return ReservasAlquilerAuto.GetFieldsForInsert();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForUpdate(ReservasAlquilerAuto entity)
        {

            IMappeableReservasAlquilerAutoObject ReservasAlquilerAuto = (IMappeableReservasAlquilerAutoObject)entity;
            return ReservasAlquilerAuto.GetFieldsForUpdate();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForDelete(ReservasAlquilerAuto entity)
        {

            IMappeableReservasAlquilerAutoObject ReservasAlquilerAuto = (IMappeableReservasAlquilerAutoObject)entity;
            return ReservasAlquilerAuto.GetFieldsForDelete();
        }


        /// <summary>
        /// Raised after insert and update
        /// </summary>
        protected override void UpdateObjectFromOutputParams(ReservasAlquilerAuto entity, object[] parameters)
        {
            // Update properties from Output parameters
            ((IMappeableReservasAlquilerAutoObject) entity).UpdateObjectFromOutputParams(parameters);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        


        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(ReservasAlquilerAuto entity)
        {
            Entities.Ubicaciones UbicacionesEntity = null; // Lazy load
            ((IMappeableReservasAlquilerAuto)entity).CompleteEntity(UbicacionesEntity);
        }


        # region CRUD Operations
        

        # endregion

        /// <summary>
        /// Delete children for this entity
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, IUniqueIdentifiable entity)
        {
                        
        }


          





        /// <summary>
        /// Get a ReservasAlquilerAuto by execute a SQL Query Text
        /// </summary>
        public ReservasAlquilerAuto GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a ReservasAlquilerAutoList by execute a SQL Query Text
        /// </summary>
        public ReservasAlquilerAutoList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// 
        /// </summary>
        public ReservasAlquilerAuto GetOne(System.Int32 IdReservaAlquilerAuto)
        {
            return base.GetOne(new ReservasAlquilerAuto(IdReservaAlquilerAuto));
        }


        // GetOne By Objects and Params
            


        

        /// <summary>
        /// 
        /// </summary>
        public ReservasAlquilerAutoList GetByUbicaciones(DbTransaction transaction, System.Int32 IdDestino)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "ReservasAlquilerAuto_GetByUbicaciones", IdDestino);
        }

        /// <summary>
        /// 
        /// </summary>
        public ReservasAlquilerAutoList GetByUbicaciones(DbTransaction transaction, IUniqueIdentifiable Ubicaciones)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "ReservasAlquilerAuto_GetByUbicaciones", Ubicaciones.Identifier());
        }

    


        

        /// <summary>
        /// 
        /// </summary>
        public ReservasAlquilerAutoList GetByUbicaciones(System.Int32 IdDestino)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "ReservasAlquilerAuto_GetByUbicaciones", IdDestino);
        }

        /// <summary>
        /// 
        /// </summary>
        public ReservasAlquilerAutoList GetByUbicaciones(IUniqueIdentifiable Ubicaciones)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "ReservasAlquilerAuto_GetByUbicaciones", Ubicaciones.Identifier());
        }

    

        /// <summary>
        /// 
        /// </summary>
        public void Delete(System.Int32 IdReservaAlquilerAuto)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "ReservasAlquilerAuto_Delete", IdReservaAlquilerAuto);
        }

        /// <summary>
        /// 
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdReservaAlquilerAuto)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "ReservasAlquilerAuto_Delete", IdReservaAlquilerAuto);
        }


        // Delete By Objects and Params
            



        

        /// <summary>
        /// 
        /// </summary>
        public void DeleteByUbicaciones(System.Int32 IdDestino)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "ReservasAlquilerAuto_DeleteByUbicaciones", IdDestino);
        }

        /// <summary>
        /// 
        /// </summary>
        public void DeleteByUbicaciones(DbTransaction transaction, System.Int32 IdDestino)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "ReservasAlquilerAuto_DeleteByUbicaciones", IdDestino);
        }


        /// <summary>
        /// 
        /// </summary>
        public void DeleteByUbicaciones(IUniqueIdentifiable Ubicaciones)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "ReservasAlquilerAuto_DeleteByUbicaciones", Ubicaciones.Identifier());
        }

        /// <summary>
        /// 
        /// </summary>
        public void DeleteByUbicaciones(DbTransaction transaction, IUniqueIdentifiable Ubicaciones)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "ReservasAlquilerAuto_DeleteByUbicaciones", Ubicaciones.Identifier());
        }


    


        //Database Queries 
        


        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }


}

namespace serin_viaticosRules.Wrappers
{
    /// <summary>
    /// 
    /// </summary>
    public class ReservasAlquilerAutoMapperWrapper
    {

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            return Instance().GetPKPropertiesNames();
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return Instance().GetMappingType();
        }



        /// <summary>
        /// 
        /// </summary>
        public serin_viaticosRules.Mappers.ReservasAlquilerAutoMapper Instance()
        {
            return serin_viaticosRules.Mappers.ReservasAlquilerAutoMapper.Instance(); 
        }
        
        /// <summary>
        /// Get a ReservasAlquilerAutoEntity by calling a Stored Procedure
        /// </summary>
        public Entities.ReservasAlquilerAuto GetOne(System.Int32 IdReservaAlquilerAuto) {
            return Instance().GetOne( IdReservaAlquilerAuto);
        }

        // GetBy Objects and Params
            

        

        /// <summary>
        /// Get a ReservasAlquilerAutoList by calling a Stored Procedure
        /// </summary>
        public Entities.ReservasAlquilerAutoList GetByUbicaciones(System.Int32 IdDestino)
        {
            return Instance().GetByUbicaciones(IdDestino);
        }

        /// <summary>
        /// Get a ReservasAlquilerAutoList by calling a Stored Procedure
        /// </summary>
        public Entities.ReservasAlquilerAutoList GetByUbicaciones(IUniqueIdentifiable Ubicaciones)
        {
            return Instance().GetByUbicaciones(Ubicaciones);
        }

    

       

        /// <summary>
        /// Delete children for ReservasAlquilerAuto
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, ReservasAlquilerAuto entity)
        {
            Instance().DeleteChildren(transaction, entity);
        }

        

            

        

        /// <summary>
        /// Delete ReservasAlquilerAuto by Ubicaciones
        /// </summary>
        public void DeleteByUbicaciones(System.Int32 IdDestino)
        {
            Instance().DeleteByUbicaciones(IdDestino);
        }

        /// <summary>
        /// Delete ReservasAlquilerAuto by Ubicaciones
        /// </summary>
        public void DeleteByUbicaciones(IUniqueIdentifiable Ubicaciones)
        {
            Instance().DeleteByUbicaciones(Ubicaciones);
        }

    
        /// <summary>
        /// Delete ReservasAlquilerAuto 
        /// </summary>
        public void Delete(System.Int32 IdReservaAlquilerAuto){
            Instance().Delete(IdReservaAlquilerAuto);
        }

        /// <summary>
        /// Delete ReservasAlquilerAuto 
        /// </summary>
        public void Delete(Entities.ReservasAlquilerAuto entity ){
            Instance().Delete(entity);
        }

        /// <summary>
        /// Save ReservasAlquilerAuto  
        /// </summary>
        public void Save(Entities.ReservasAlquilerAuto entity){
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert ReservasAlquilerAuto 
        /// </summary>
        public void Insert(Entities.ReservasAlquilerAuto entity){
            Instance().Insert(entity);
        }

        /// <summary>
        /// GetAll ReservasAlquilerAuto 
        /// </summary>
        public Entities.ReservasAlquilerAutoList GetAll(){  
            return Instance().GetAll();
        }

        /// <summary>
        /// Save ReservasAlquilerAuto 
        /// </summary>
        public void Save(System.Int32 IdReservaAlquilerAuto, System.Int32 IdDestino, System.Int32 CantPasajeros, System.String Marca, System.String Modelo, System.DateTime FechaDesde, System.DateTime FechaHasta, System.Decimal Precio){
            Entities.ReservasAlquilerAuto entity = Instance().GetOne(IdReservaAlquilerAuto);
            if (entity == null)
                throw new ApplicationException(String.Format("Entity not found. IUniqueIdentifiable Values: {0} = {1}", "IdReservaAlquilerAuto", IdReservaAlquilerAuto));

            entity.IdDestino = IdDestino;
            entity.CantPasajeros = CantPasajeros;
            entity.Marca = Marca;
            entity.Modelo = Modelo;
            entity.FechaDesde = FechaDesde;
            entity.FechaHasta = FechaHasta;
            entity.Precio = Precio;
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert ReservasAlquilerAuto
        /// </summary>
        public void Insert(System.Int32 IdDestino, System.Int32 CantPasajeros, System.String Marca, System.String Modelo, System.DateTime FechaDesde, System.DateTime FechaHasta, System.Decimal Precio){
            Entities.ReservasAlquilerAuto entity = new Entities.ReservasAlquilerAuto();

            entity.IdDestino = IdDestino;
            entity.CantPasajeros = CantPasajeros;
            entity.Marca = Marca;
            entity.Modelo = Modelo;
            entity.FechaDesde = FechaDesde;
            entity.FechaHasta = FechaHasta;
            entity.Precio = Precio;
            Instance().Insert(entity);
        }


        //Database Queries 
        


    }
}





namespace serin_viaticosRules.Loaders
{

    /// <summary>
    /// 
    /// </summary>
    public partial class ReservasAlquilerAutoLoader<T> : BaseLoader< T, ReservasAlquilerAuto, ObjectList<T>>, IGenericGateway where T : ReservasAlquilerAuto, new()
    {

        #region "Singleton"

        static ReservasAlquilerAutoLoader<T> _instance;

        private ReservasAlquilerAutoLoader()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static ReservasAlquilerAutoLoader<T> Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new ReservasAlquilerAutoLoader<T>();
                else {
                    ReservasAlquilerAutoLoader<T> inst = HttpContext.Current.Items["serin_viaticosRules.ReservasAlquilerAutoLoaderSingleton"] as ReservasAlquilerAutoLoader<T>;
                    if (inst == null) {
                        inst = new ReservasAlquilerAutoLoader<T>();
                        HttpContext.Current.Items.Add("serin_viaticosRules.ReservasAlquilerAutoLoaderSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"IdReservaAlquilerAuto"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(ReservasAlquilerAuto);
        }


        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "ReservasAlquilerAuto"; }
        }

        
        
        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, ReservasAlquilerAuto entity)
        {
            
            IMappeableReservasAlquilerAutoObject ReservasAlquilerAuto = (IMappeableReservasAlquilerAutoObject)entity;
            ReservasAlquilerAuto.HydrateFields(
            reader.GetInt32(0),
reader.GetInt32(1),
reader.GetInt32(2),
reader.GetString(3),
reader.GetString(4),
reader.GetDateTime(5),
reader.GetDateTime(6),
(reader.IsDBNull(7)) ? new System.Nullable<System.Decimal>() : reader.GetDecimal(7));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        
    

        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(T entity)
        {
            Entities.Ubicaciones UbicacionesEntity = null; // Lazy load
            ((IMappeableReservasAlquilerAuto)entity).CompleteEntity(UbicacionesEntity);
        }


        



        /// <summary>
        /// Get a ReservasAlquilerAuto by execute a SQL Query Text
        /// </summary>
        public T GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a ReservasAlquilerAutoList by execute a SQL Query Text
        /// </summary>
        public ObjectList<T> GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }

        /// <summary>
        /// GetOne By Params
        /// </summary>
        public T GetOne(System.Int32 IdReservaAlquilerAuto)
        {
            return base.GetObjectByAnyStoredProcedure(StoredProceduresPrefix() + "ReservasAlquilerAuto_GetOne", IdReservaAlquilerAuto);
        }


        // GetOne By Objects and Params
            


        

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByUbicaciones(DbTransaction transaction, System.Int32 IdDestino)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "ReservasAlquilerAuto_GetByUbicaciones", IdDestino);
        }

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByUbicaciones(DbTransaction transaction, IUniqueIdentifiable Ubicaciones)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "ReservasAlquilerAuto_GetByUbicaciones", Ubicaciones.Identifier());
        }

    


        

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByUbicaciones(System.Int32 IdDestino)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "ReservasAlquilerAuto_GetByUbicaciones", IdDestino);
        }

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByUbicaciones(IUniqueIdentifiable Ubicaciones)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "ReservasAlquilerAuto_GetByUbicaciones", Ubicaciones.Identifier());
        }

    

        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion

    }
}





