
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is SolicitudesCategoriasMapper.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using serin_viaticosRules.Entities;
using serin_viaticosRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data.Common;
using System.Reflection;
using System.Web;
using System.Data;

namespace serin_viaticosRules.Mappers
{

    
    /// <summary>
    /// 
    /// </summary>
    public partial class SolicitudesCategoriasMapper : BaseGateway<SolicitudesCategorias, SolicitudesCategoriasList>, IGenericGateway
    {


        #region "Singleton"

        static SolicitudesCategoriasMapper _instance;

        private SolicitudesCategoriasMapper()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static SolicitudesCategoriasMapper Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new SolicitudesCategoriasMapper();
                else {
                    SolicitudesCategoriasMapper inst = HttpContext.Current.Items["serin_viaticosRules.SolicitudesCategoriasMapperSingleton"] as SolicitudesCategoriasMapper;
                    if (inst == null) {
                        inst = new SolicitudesCategoriasMapper();
                        HttpContext.Current.Items.Add("serin_viaticosRules.SolicitudesCategoriasMapperSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"IdSolicitudCategoria"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(SolicitudesCategorias);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "SolicitudesCategorias"; }
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string RuleName
        {
            get {return typeof(SolicitudesCategoriasMapper).FullName;}
        }


        

        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, SolicitudesCategorias entity)
        {
            
            IMappeableSolicitudesCategoriasObject SolicitudesCategorias = (IMappeableSolicitudesCategoriasObject)entity;
            SolicitudesCategorias.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1),
reader.GetBoolean(2),
reader.GetString(3));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForInsert(SolicitudesCategorias entity)
        {

            IMappeableSolicitudesCategoriasObject SolicitudesCategorias = (IMappeableSolicitudesCategoriasObject)entity;
            return SolicitudesCategorias.GetFieldsForInsert();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForUpdate(SolicitudesCategorias entity)
        {

            IMappeableSolicitudesCategoriasObject SolicitudesCategorias = (IMappeableSolicitudesCategoriasObject)entity;
            return SolicitudesCategorias.GetFieldsForUpdate();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForDelete(SolicitudesCategorias entity)
        {

            IMappeableSolicitudesCategoriasObject SolicitudesCategorias = (IMappeableSolicitudesCategoriasObject)entity;
            return SolicitudesCategorias.GetFieldsForDelete();
        }


        /// <summary>
        /// Raised after insert and update
        /// </summary>
        protected override void UpdateObjectFromOutputParams(SolicitudesCategorias entity, object[] parameters)
        {
            // Update properties from Output parameters
            ((IMappeableSolicitudesCategoriasObject) entity).UpdateObjectFromOutputParams(parameters);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        


        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(SolicitudesCategorias entity)
        {
            
            ((IMappeableSolicitudesCategorias)entity).CompleteEntity();
        }


        # region CRUD Operations
        

        # endregion

        /// <summary>
        /// Delete children for this entity
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, IUniqueIdentifiable entity)
        {
                        
        }


          





        /// <summary>
        /// Get a SolicitudesCategorias by execute a SQL Query Text
        /// </summary>
        public SolicitudesCategorias GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a SolicitudesCategoriasList by execute a SQL Query Text
        /// </summary>
        public SolicitudesCategoriasList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// 
        /// </summary>
        public SolicitudesCategorias GetOne(System.Int32 IdSolicitudCategoria)
        {
            return base.GetOne(new SolicitudesCategorias(IdSolicitudCategoria));
        }


        // GetOne By Objects and Params
            


        


        

        /// <summary>
        /// 
        /// </summary>
        public void Delete(System.Int32 IdSolicitudCategoria)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "SolicitudesCategorias_Delete", IdSolicitudCategoria);
        }

        /// <summary>
        /// 
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdSolicitudCategoria)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "SolicitudesCategorias_Delete", IdSolicitudCategoria);
        }


        // Delete By Objects and Params
            



        


        //Database Queries 
        


        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }


}

namespace serin_viaticosRules.Wrappers
{
    /// <summary>
    /// 
    /// </summary>
    public class SolicitudesCategoriasMapperWrapper
    {

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            return Instance().GetPKPropertiesNames();
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return Instance().GetMappingType();
        }



        /// <summary>
        /// 
        /// </summary>
        public serin_viaticosRules.Mappers.SolicitudesCategoriasMapper Instance()
        {
            return serin_viaticosRules.Mappers.SolicitudesCategoriasMapper.Instance(); 
        }
        
        /// <summary>
        /// Get a SolicitudesCategoriasEntity by calling a Stored Procedure
        /// </summary>
        public Entities.SolicitudesCategorias GetOne(System.Int32 IdSolicitudCategoria) {
            return Instance().GetOne( IdSolicitudCategoria);
        }

        // GetBy Objects and Params
            

        

       

        /// <summary>
        /// Delete children for SolicitudesCategorias
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, SolicitudesCategorias entity)
        {
            Instance().DeleteChildren(transaction, entity);
        }

        

            

        
        /// <summary>
        /// Delete SolicitudesCategorias 
        /// </summary>
        public void Delete(System.Int32 IdSolicitudCategoria){
            Instance().Delete(IdSolicitudCategoria);
        }

        /// <summary>
        /// Delete SolicitudesCategorias 
        /// </summary>
        public void Delete(Entities.SolicitudesCategorias entity ){
            Instance().Delete(entity);
        }

        /// <summary>
        /// Save SolicitudesCategorias  
        /// </summary>
        public void Save(Entities.SolicitudesCategorias entity){
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert SolicitudesCategorias 
        /// </summary>
        public void Insert(Entities.SolicitudesCategorias entity){
            Instance().Insert(entity);
        }

        /// <summary>
        /// GetAll SolicitudesCategorias 
        /// </summary>
        public Entities.SolicitudesCategoriasList GetAll(){  
            return Instance().GetAll();
        }

        /// <summary>
        /// Save SolicitudesCategorias 
        /// </summary>
        public void Save(System.Int32 IdSolicitudCategoria, System.String Nombre, System.Boolean Activo, System.String EmailNotificacion){
            Entities.SolicitudesCategorias entity = Instance().GetOne(IdSolicitudCategoria);
            if (entity == null)
                throw new ApplicationException(String.Format("Entity not found. IUniqueIdentifiable Values: {0} = {1}", "IdSolicitudCategoria", IdSolicitudCategoria));

            entity.Nombre = Nombre;
            entity.Activo = Activo;
            entity.EmailNotificacion = EmailNotificacion;
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert SolicitudesCategorias
        /// </summary>
        public void Insert(System.String Nombre, System.Boolean Activo, System.String EmailNotificacion){
            Entities.SolicitudesCategorias entity = new Entities.SolicitudesCategorias();

            entity.Nombre = Nombre;
            entity.Activo = Activo;
            entity.EmailNotificacion = EmailNotificacion;
            Instance().Insert(entity);
        }


        //Database Queries 
        


    }
}





namespace serin_viaticosRules.Loaders
{

    /// <summary>
    /// 
    /// </summary>
    public partial class SolicitudesCategoriasLoader<T> : BaseLoader< T, SolicitudesCategorias, ObjectList<T>>, IGenericGateway where T : SolicitudesCategorias, new()
    {

        #region "Singleton"

        static SolicitudesCategoriasLoader<T> _instance;

        private SolicitudesCategoriasLoader()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static SolicitudesCategoriasLoader<T> Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new SolicitudesCategoriasLoader<T>();
                else {
                    SolicitudesCategoriasLoader<T> inst = HttpContext.Current.Items["serin_viaticosRules.SolicitudesCategoriasLoaderSingleton"] as SolicitudesCategoriasLoader<T>;
                    if (inst == null) {
                        inst = new SolicitudesCategoriasLoader<T>();
                        HttpContext.Current.Items.Add("serin_viaticosRules.SolicitudesCategoriasLoaderSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"IdSolicitudCategoria"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(SolicitudesCategorias);
        }


        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "SolicitudesCategorias"; }
        }

        
        
        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, SolicitudesCategorias entity)
        {
            
            IMappeableSolicitudesCategoriasObject SolicitudesCategorias = (IMappeableSolicitudesCategoriasObject)entity;
            SolicitudesCategorias.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1),
reader.GetBoolean(2),
reader.GetString(3));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        
    

        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(T entity)
        {
            
            ((IMappeableSolicitudesCategorias)entity).CompleteEntity();
        }


        



        /// <summary>
        /// Get a SolicitudesCategorias by execute a SQL Query Text
        /// </summary>
        public T GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a SolicitudesCategoriasList by execute a SQL Query Text
        /// </summary>
        public ObjectList<T> GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }

        /// <summary>
        /// GetOne By Params
        /// </summary>
        public T GetOne(System.Int32 IdSolicitudCategoria)
        {
            return base.GetObjectByAnyStoredProcedure(StoredProceduresPrefix() + "SolicitudesCategorias_GetOne", IdSolicitudCategoria);
        }


        // GetOne By Objects and Params
            


        


        

        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion

    }
}





