
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is ItinerarioEntity.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using serin_viaticosRules.Objects;



using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using System;

namespace serin_viaticosRules.Entities
{

    /// <summary>
    /// 
    /// </summary>
    public partial class Itinerario : Objects.ItinerarioObject, IMappeableItinerario, IEquatable<Itinerario>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public Itinerario()
            :base()
        {
            
        }

        /// <summary>
        /// 
        /// </summary>
        public Itinerario(
			System.Int32 IdItinerario)
            : base()
        {

			_IdItinerario = IdItinerario;

            
            Initialized();
        }

        

        /// <summary>
        /// 
        /// </summary>
        public Itinerario(
			System.Int32 IdItinerario,
			System.DateTime Fecha,
			System.Boolean IdaVuelta,
			System.Nullable<System.DateTime> FechaVuelta,
			System.Nullable<System.Decimal> Km)
            : base()
        {

			_IdItinerario = IdItinerario;
			_Fecha = Fecha;
			_IdaVuelta = IdaVuelta;
			_FechaVuelta = FechaVuelta;
			_Km = Km;

            
            Initialized();
        }
        
        #endregion

        #region "Fields"

        
        #endregion

        #region "Properties"
        
        #endregion

        /// <summary>
        /// Returns de original value of entity since was created or restored.
        /// </summary>
        public new Itinerario OriginalValue()
        {
            return (Itinerario)base.OriginalValue();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            Itinerario newObject;            
            

            newObject = (Itinerario)this.MemberwiseClone();
            // Entities
            
            // Colections
            
            // OriginalValue
            Itinerario newOriginalValue;
            if (base._OriginalValue != null)
            {
                newOriginalValue = (Itinerario)this.OriginalValue().MemberwiseClone();
                // Entities
                
                // Colections
                            
                newObject._OriginalValue = newOriginalValue;

            }
            return newObject;            
        }



        /// <summary>
        /// 
        /// </summary>
        void IMappeableItinerario.CompleteEntity()
        {
        
        }
        

        /// <summary>
        /// 
        /// </summary>
        void IMappeableItinerario.SetFKValuesForChilds(Itinerario entity)
        {
                
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(Itinerario other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        } 

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableItinerario
    {
        /// <summary>
        /// 
        /// </summary>
        void CompleteEntity();
        
        /// <summary>
        /// 
        /// </summary>
        void SetFKValuesForChilds(Itinerario entity);
    }

        /// <summary>
        /// 
        /// </summary>
    public partial class ItinerarioList : ObjectList<Itinerario>
    {
    }
}
namespace serin_viaticosRules.Views
{
        /// <summary>
        /// 
        /// </summary>
    public partial class ItinerarioListView
        : ObjectListView<Entities.Itinerario>
    {
        /// <summary>
        /// 
        /// </summary>
        public ItinerarioListView(Entities.ItinerarioList list): base(list)
        {
        }
    }
}


