
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is PerfilesEntity.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using serin_viaticosRules.Objects;



using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using System;

namespace serin_viaticosRules.Entities
{

    /// <summary>
    /// 
    /// </summary>
    public partial class Perfiles : Objects.PerfilesObject, IMappeablePerfiles, IEquatable<Perfiles>, ICloneable
    {
       
        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public Perfiles()
            :base()
        {
            
        }

        /// <summary>
        /// 
        /// </summary>
        public Perfiles(
			System.Int32 IdPerfil)
            : base()
        {

			_IdPerfil = IdPerfil;

            
            Initialized();
        }

        

        /// <summary>
        /// 
        /// </summary>
        public Perfiles(
			System.Int32 IdPerfil,
			System.String Nombre,
			System.Boolean Activo,
			System.Boolean RequiereAutorizacion,
			System.Boolean Admin)
            : base()
        {

			_IdPerfil = IdPerfil;
			_Nombre = Nombre;
			_Activo = Activo;
			_RequiereAutorizacion = RequiereAutorizacion;
			_Admin = Admin;

            
            Initialized();
        }
        
        #endregion

        #region "Fields"

        
        #endregion

        #region "Properties"
        
        #endregion

        /// <summary>
        /// Returns de original value of entity since was created or restored.
        /// </summary>
        public new Perfiles OriginalValue()
        {
            return (Perfiles)base.OriginalValue();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            Perfiles newObject;            
            

            newObject = (Perfiles)this.MemberwiseClone();
            // Entities
            
            // Colections
            
            // OriginalValue
            Perfiles newOriginalValue;
            if (base._OriginalValue != null)
            {
                newOriginalValue = (Perfiles)this.OriginalValue().MemberwiseClone();
                // Entities
                
                // Colections
                            
                newObject._OriginalValue = newOriginalValue;

            }
            return newObject;            
        }



        /// <summary>
        /// 
        /// </summary>
        void IMappeablePerfiles.CompleteEntity()
        {
        
        }
        

        /// <summary>
        /// 
        /// </summary>
        void IMappeablePerfiles.SetFKValuesForChilds(Perfiles entity)
        {
                
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(Perfiles other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        } 

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeablePerfiles
    {
        /// <summary>
        /// 
        /// </summary>
        void CompleteEntity();
        
        /// <summary>
        /// 
        /// </summary>
        void SetFKValuesForChilds(Perfiles entity);
    }

        /// <summary>
        /// 
        /// </summary>
    public partial class PerfilesList : ObjectList<Perfiles>
    {
    }
}
namespace serin_viaticosRules.Views
{
        /// <summary>
        /// 
        /// </summary>
    public partial class PerfilesListView
        : ObjectListView<Entities.Perfiles>
    {
        /// <summary>
        /// 
        /// </summary>
        public PerfilesListView(Entities.PerfilesList list): base(list)
        {
        }
    }
}


