
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is ReservasAlquilerAutoEntity.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using serin_viaticosRules.Objects;



using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using System;

namespace serin_viaticosRules.Entities
{

    /// <summary>
    /// 
    /// </summary>
    public partial class ReservasAlquilerAuto : Objects.ReservasAlquilerAutoObject, IMappeableReservasAlquilerAuto, IEquatable<ReservasAlquilerAuto>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public ReservasAlquilerAuto()
            :base()
        {
            if (_UbicacionesEntity == null) _UbicacionesEntity = new Entities.Ubicaciones();

        }

        /// <summary>
        /// 
        /// </summary>
        public ReservasAlquilerAuto(
			System.Int32 IdReservaAlquilerAuto)
            : base()
        {

			_IdReservaAlquilerAuto = IdReservaAlquilerAuto;

            if (_UbicacionesEntity == null) _UbicacionesEntity = new Entities.Ubicaciones();

            Initialized();
        }

        

        /// <summary>
        /// 
        /// </summary>
        public ReservasAlquilerAuto(
			System.Int32 IdReservaAlquilerAuto,
			System.Int32 IdDestino,
			System.Int32 CantPasajeros,
			System.String Marca,
			System.String Modelo,
			System.DateTime FechaDesde,
			System.DateTime FechaHasta,
			System.Nullable<System.Decimal> Precio)
            : base()
        {

			_IdReservaAlquilerAuto = IdReservaAlquilerAuto;
			_IdDestino = IdDestino;
			_CantPasajeros = CantPasajeros;
			_Marca = Marca;
			_Modelo = Modelo;
			_FechaDesde = FechaDesde;
			_FechaHasta = FechaHasta;
			_Precio = Precio;

            if (_UbicacionesEntity == null) _UbicacionesEntity = new Entities.Ubicaciones();

            Initialized();
        }
        
        #endregion

        #region "Fields"

        /// <summary>
/// 
/// </summary>
protected Entities.Ubicaciones _UbicacionesEntity;

        #endregion

        #region "Properties"
        
bool _UbicacionesEntityFetched;

        /// <summary>
        /// 
        /// </summary>
        public virtual Entities.Ubicaciones UbicacionesEntity
        {
            get
            {
                if (_UbicacionesEntity== null  && ! _UbicacionesEntityFetched ) {
_UbicacionesEntityFetched = true;
Entities.Ubicaciones _UbicacionesEntityTemp = new Entities.Ubicaciones(this.IdDestino); 
ILazyProvider lazyProvider = LazyProviderFactory.Get(typeof(Entities.Ubicaciones));
 _UbicacionesEntity = lazyProvider.GetEntity(typeof(Entities.Ubicaciones), _UbicacionesEntityTemp) as Entities.Ubicaciones;
}

                return _UbicacionesEntity;
            }
            set
            {
                base.PropertyModified();
                _UbicacionesEntity = value;
                if (value != null) {
   _IdDestino = value.IdUbicacion;

} else {
   _IdDestino = System.Int32.MinValue;

}

            }
        }
        
        #endregion

        /// <summary>
        /// Returns de original value of entity since was created or restored.
        /// </summary>
        public new ReservasAlquilerAuto OriginalValue()
        {
            return (ReservasAlquilerAuto)base.OriginalValue();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            ReservasAlquilerAuto newObject;            
            

            newObject = (ReservasAlquilerAuto)this.MemberwiseClone();
            // Entities
                         
            if (this._UbicacionesEntity != null)
            {
                newObject._UbicacionesEntity = (Entities.Ubicaciones)((ICloneable)this._UbicacionesEntity).Clone();
            }
            
            // Colections
            
            // OriginalValue
            ReservasAlquilerAuto newOriginalValue;
            if (base._OriginalValue != null)
            {
                newOriginalValue = (ReservasAlquilerAuto)this.OriginalValue().MemberwiseClone();
                // Entities
                             
                if (this.OriginalValue()._UbicacionesEntity != null)
                {
                    newOriginalValue._UbicacionesEntity = (Entities.Ubicaciones)((ICloneable)this.OriginalValue()._UbicacionesEntity).Clone();
                }
                
                // Colections
                            
                newObject._OriginalValue = newOriginalValue;

            }
            return newObject;            
        }



        /// <summary>
        /// 
        /// </summary>
        void IMappeableReservasAlquilerAuto.CompleteEntity(Entities.Ubicaciones UbicacionesEntity)
        {
        _UbicacionesEntity = UbicacionesEntity;
        }
        
        bool IMappeableReservasAlquilerAuto.IsUbicacionesEntityNull()
        {
            return (_UbicacionesEntity == null);
        }
        

        /// <summary>
        /// 
        /// </summary>
        void IMappeableReservasAlquilerAuto.SetFKValuesForChilds(ReservasAlquilerAuto entity)
        {
                
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(ReservasAlquilerAuto other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        } 

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableReservasAlquilerAuto
    {
        /// <summary>
        /// 
        /// </summary>
        void CompleteEntity(Entities.Ubicaciones UbicacionesEntity);
        
        /// <summary>
        /// 
        /// </summary>
        bool IsUbicacionesEntityNull();
        
        /// <summary>
        /// 
        /// </summary>
        void SetFKValuesForChilds(ReservasAlquilerAuto entity);
    }

        /// <summary>
        /// 
        /// </summary>
    public partial class ReservasAlquilerAutoList : ObjectList<ReservasAlquilerAuto>
    {
    }
}
namespace serin_viaticosRules.Views
{
        /// <summary>
        /// 
        /// </summary>
    public partial class ReservasAlquilerAutoListView
        : ObjectListView<Entities.ReservasAlquilerAuto>
    {
        /// <summary>
        /// 
        /// </summary>
        public ReservasAlquilerAutoListView(Entities.ReservasAlquilerAutoList list): base(list)
        {
        }
    }
}


