
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is SolicitudesUsuariosEntity.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using serin_viaticosRules.Objects;



using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using System;

namespace serin_viaticosRules.Entities
{

    /// <summary>
    /// 
    /// </summary>
    public partial class SolicitudesUsuarios : Objects.SolicitudesUsuariosObject, IMappeableSolicitudesUsuarios, IEquatable<SolicitudesUsuarios>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public SolicitudesUsuarios()
            :base()
        {
            if (_SolicitudesEntity == null) _SolicitudesEntity = new Entities.Solicitudes();

        }

        /// <summary>
        /// 
        /// </summary>
        public SolicitudesUsuarios(
			System.Int32 IdSolicitudUsuario)
            : base()
        {

			_IdSolicitudUsuario = IdSolicitudUsuario;

            if (_SolicitudesEntity == null) _SolicitudesEntity = new Entities.Solicitudes();

            Initialized();
        }

        

        /// <summary>
        /// 
        /// </summary>
        public SolicitudesUsuarios(
			System.Int32 IdSolicitudUsuario,
			System.Int32 IdSolicitud,
			System.Int32 IdUsuario,
			System.Nullable<System.Decimal> MontoAnticipo)
            : base()
        {

			_IdSolicitudUsuario = IdSolicitudUsuario;
			_IdSolicitud = IdSolicitud;
			_IdUsuario = IdUsuario;
			_MontoAnticipo = MontoAnticipo;

            if (_SolicitudesEntity == null) _SolicitudesEntity = new Entities.Solicitudes();

            Initialized();
        }
        
        #endregion

        #region "Fields"

        /// <summary>
/// 
/// </summary>
protected Entities.Solicitudes _SolicitudesEntity;

        #endregion

        #region "Properties"
        
bool _SolicitudesEntityFetched;

        /// <summary>
        /// 
        /// </summary>
        public virtual Entities.Solicitudes SolicitudesEntity
        {
            get
            {
                if (_SolicitudesEntity== null  && ! _SolicitudesEntityFetched ) {
_SolicitudesEntityFetched = true;
Entities.Solicitudes _SolicitudesEntityTemp = new Entities.Solicitudes(this.IdSolicitud); 
ILazyProvider lazyProvider = LazyProviderFactory.Get(typeof(Entities.Solicitudes));
 _SolicitudesEntity = lazyProvider.GetEntity(typeof(Entities.Solicitudes), _SolicitudesEntityTemp) as Entities.Solicitudes;
}

                return _SolicitudesEntity;
            }
            set
            {
                base.PropertyModified();
                _SolicitudesEntity = value;
                if (value != null) {
   _IdSolicitud = value.IdSolicitud;

} else {
   _IdSolicitud = System.Int32.MinValue;

}

            }
        }
        
        #endregion

        /// <summary>
        /// Returns de original value of entity since was created or restored.
        /// </summary>
        public new SolicitudesUsuarios OriginalValue()
        {
            return (SolicitudesUsuarios)base.OriginalValue();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            SolicitudesUsuarios newObject;            
            

            newObject = (SolicitudesUsuarios)this.MemberwiseClone();
            // Entities
                         
            if (this._SolicitudesEntity != null)
            {
                newObject._SolicitudesEntity = (Entities.Solicitudes)((ICloneable)this._SolicitudesEntity).Clone();
            }
            
            // Colections
            
            // OriginalValue
            SolicitudesUsuarios newOriginalValue;
            if (base._OriginalValue != null)
            {
                newOriginalValue = (SolicitudesUsuarios)this.OriginalValue().MemberwiseClone();
                // Entities
                             
                if (this.OriginalValue()._SolicitudesEntity != null)
                {
                    newOriginalValue._SolicitudesEntity = (Entities.Solicitudes)((ICloneable)this.OriginalValue()._SolicitudesEntity).Clone();
                }
                
                // Colections
                            
                newObject._OriginalValue = newOriginalValue;

            }
            return newObject;            
        }



        /// <summary>
        /// 
        /// </summary>
        void IMappeableSolicitudesUsuarios.CompleteEntity(Entities.Solicitudes SolicitudesEntity)
        {
        _SolicitudesEntity = SolicitudesEntity;
        }
        
        bool IMappeableSolicitudesUsuarios.IsSolicitudesEntityNull()
        {
            return (_SolicitudesEntity == null);
        }
        

        /// <summary>
        /// 
        /// </summary>
        void IMappeableSolicitudesUsuarios.SetFKValuesForChilds(SolicitudesUsuarios entity)
        {
                
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(SolicitudesUsuarios other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        } 

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableSolicitudesUsuarios
    {
        /// <summary>
        /// 
        /// </summary>
        void CompleteEntity(Entities.Solicitudes SolicitudesEntity);
        
        /// <summary>
        /// 
        /// </summary>
        bool IsSolicitudesEntityNull();
        
        /// <summary>
        /// 
        /// </summary>
        void SetFKValuesForChilds(SolicitudesUsuarios entity);
    }

        /// <summary>
        /// 
        /// </summary>
    public partial class SolicitudesUsuariosList : ObjectList<SolicitudesUsuarios>
    {
    }
}
namespace serin_viaticosRules.Views
{
        /// <summary>
        /// 
        /// </summary>
    public partial class SolicitudesUsuariosListView
        : ObjectListView<Entities.SolicitudesUsuarios>
    {
        /// <summary>
        /// 
        /// </summary>
        public SolicitudesUsuariosListView(Entities.SolicitudesUsuariosList list): base(list)
        {
        }
    }
}


