
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is UbicacionesEntity.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using serin_viaticosRules.Objects;



using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using System;

namespace serin_viaticosRules.Entities
{

    /// <summary>
    /// 
    /// </summary>
    public partial class Ubicaciones : Objects.UbicacionesObject, IMappeableUbicaciones, IEquatable<Ubicaciones>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public Ubicaciones()
            :base()
        {
            
        }

        /// <summary>
        /// 
        /// </summary>
        public Ubicaciones(
			System.Int32 IdUbicacion)
            : base()
        {

			_IdUbicacion = IdUbicacion;

            
            Initialized();
        }

        

        /// <summary>
        /// 
        /// </summary>
        public Ubicaciones(
			System.Int32 IdUbicacion,
			System.String Nombre,
			System.Nullable<System.Decimal> Lat,
			System.Nullable<System.Decimal> Lng)
            : base()
        {

			_IdUbicacion = IdUbicacion;
			_Nombre = Nombre;
			_Lat = Lat;
			_Lng = Lng;

            
            Initialized();
        }
        
        #endregion

        #region "Fields"

        
        #endregion

        #region "Properties"
        
        #endregion

        /// <summary>
        /// Returns de original value of entity since was created or restored.
        /// </summary>
        public new Ubicaciones OriginalValue()
        {
            return (Ubicaciones)base.OriginalValue();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            Ubicaciones newObject;            
            

            newObject = (Ubicaciones)this.MemberwiseClone();
            // Entities
            
            // Colections
            
            // OriginalValue
            Ubicaciones newOriginalValue;
            if (base._OriginalValue != null)
            {
                newOriginalValue = (Ubicaciones)this.OriginalValue().MemberwiseClone();
                // Entities
                
                // Colections
                            
                newObject._OriginalValue = newOriginalValue;

            }
            return newObject;            
        }



        /// <summary>
        /// 
        /// </summary>
        void IMappeableUbicaciones.CompleteEntity()
        {
        
        }
        

        /// <summary>
        /// 
        /// </summary>
        void IMappeableUbicaciones.SetFKValuesForChilds(Ubicaciones entity)
        {
                
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(Ubicaciones other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        } 

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableUbicaciones
    {
        /// <summary>
        /// 
        /// </summary>
        void CompleteEntity();
        
        /// <summary>
        /// 
        /// </summary>
        void SetFKValuesForChilds(Ubicaciones entity);
    }

        /// <summary>
        /// 
        /// </summary>
    public partial class UbicacionesList : ObjectList<Ubicaciones>
    {
    }
}
namespace serin_viaticosRules.Views
{
        /// <summary>
        /// 
        /// </summary>
    public partial class UbicacionesListView
        : ObjectListView<Entities.Ubicaciones>
    {
        /// <summary>
        /// 
        /// </summary>
        public UbicacionesListView(Entities.UbicacionesList list): base(list)
        {
        }
    }
}


