
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is UsuariosDependenciaEntity.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using serin_viaticosRules.Objects;



using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using System;

namespace serin_viaticosRules.Entities
{

    /// <summary>
    /// 
    /// </summary>
    public partial class UsuariosDependencia : Objects.UsuariosDependenciaObject, IMappeableUsuariosDependencia, IEquatable<UsuariosDependencia>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public UsuariosDependencia()
            :base()
        {
            
        }

        /// <summary>
        /// 
        /// </summary>
        public UsuariosDependencia(
			System.Int32 IdDependenciaUsuario)
            : base()
        {

			_IdDependenciaUsuario = IdDependenciaUsuario;

            
            Initialized();
        }

        

        /// <summary>
        /// 
        /// </summary>
        public UsuariosDependencia(
			System.Int32 IdDependenciaUsuario,
			System.Int32 IdUsuarioPadre,
			System.Int32 IdUsuarioHijo)
            : base()
        {

			_IdDependenciaUsuario = IdDependenciaUsuario;
			_IdUsuarioPadre = IdUsuarioPadre;
			_IdUsuarioHijo = IdUsuarioHijo;

            
            Initialized();
        }
        
        #endregion

        #region "Fields"

        
        #endregion

        #region "Properties"
        
        #endregion

        /// <summary>
        /// Returns de original value of entity since was created or restored.
        /// </summary>
        public new UsuariosDependencia OriginalValue()
        {
            return (UsuariosDependencia)base.OriginalValue();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            UsuariosDependencia newObject;            
            

            newObject = (UsuariosDependencia)this.MemberwiseClone();
            // Entities
            
            // Colections
            
            // OriginalValue
            UsuariosDependencia newOriginalValue;
            if (base._OriginalValue != null)
            {
                newOriginalValue = (UsuariosDependencia)this.OriginalValue().MemberwiseClone();
                // Entities
                
                // Colections
                            
                newObject._OriginalValue = newOriginalValue;

            }
            return newObject;            
        }



        /// <summary>
        /// 
        /// </summary>
        void IMappeableUsuariosDependencia.CompleteEntity()
        {
        
        }
        

        /// <summary>
        /// 
        /// </summary>
        void IMappeableUsuariosDependencia.SetFKValuesForChilds(UsuariosDependencia entity)
        {
                
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(UsuariosDependencia other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        } 

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableUsuariosDependencia
    {
        /// <summary>
        /// 
        /// </summary>
        void CompleteEntity();
        
        /// <summary>
        /// 
        /// </summary>
        void SetFKValuesForChilds(UsuariosDependencia entity);
    }

        /// <summary>
        /// 
        /// </summary>
    public partial class UsuariosDependenciaList : ObjectList<UsuariosDependencia>
    {
    }
}
namespace serin_viaticosRules.Views
{
        /// <summary>
        /// 
        /// </summary>
    public partial class UsuariosDependenciaListView
        : ObjectListView<Entities.UsuariosDependencia>
    {
        /// <summary>
        /// 
        /// </summary>
        public UsuariosDependenciaListView(Entities.UsuariosDependenciaList list): base(list)
        {
        }
    }
}


