
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 27/09/2022 - 8:10
// This is a partial class file. The other one is PerfilesUsuariosMapper.Auto.cs
// You can edit this file as your wish.
//------------------------------------------------------------------------------

using serin_viaticosRules.Objects;
using serin_viaticosRules.Entities;
using Cooperator.Framework.Core;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using System.Data.Common;
using System.Reflection;
using System;

namespace serin_viaticosRules.Mappers
{

    /// <summary>
    /// Mapper for PerfilesUsuarios entity
    /// This class provide persistence methods for this entity
    /// </summary>
    public  partial class PerfilesUsuariosMapper
    {
        // /// <summary>
        // /// Enables GetObjectBySQLText and GetObjectListBySQLText methods.
        // /// </summary>
        //protected override bool SQLQueriesEnabled()
        //{
        //    return true;
        //}

        // /// <summary>
        // /// Checks for security ritghs
        // /// </summary>
        //protected override bool CheckForSecurityRights(SecurityRights action, PerfilesUsuariosList ObjectListOrEntityList)
        //{
        //    switch (action)
        //    {
        //        case SecurityRights.Read:
        //            return true;
        //        case SecurityRights.Insert:
        //            return true;
        //        case SecurityRights.Update:
        //            return true;
        //        case SecurityRights.Delete:
        //            return true;
        //    }
        //    return false;
        //}

    }

}


namespace serin_viaticosRules.Loaders
{

    /// <summary>
    /// Loader for PerfilesUsuarios entity
    /// This class provide get methods for this entity
    /// </summary>
    public partial class PerfilesUsuariosLoader
    {
    }

}



