
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 20/10/2022 - 11:24
// This is a partial class file. The other one is SolicitudesEstadosMapper.Auto.cs
// You can edit this file as your wish.
//------------------------------------------------------------------------------

using serin_viaticosRules.Objects;
using serin_viaticosRules.Entities;
using Cooperator.Framework.Core;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using System.Data.Common;
using System.Reflection;
using System;

namespace serin_viaticosRules.Mappers
{

    /// <summary>
    /// Mapper for SolicitudesEstados entity
    /// This class provide persistence methods for this entity
    /// </summary>
    public  partial class SolicitudesEstadosMapper
    {
        // /// <summary>
        // /// Enables GetObjectBySQLText and GetObjectListBySQLText methods.
        // /// </summary>
        //protected override bool SQLQueriesEnabled()
        //{
        //    return true;
        //}

        // /// <summary>
        // /// Checks for security ritghs
        // /// </summary>
        //protected override bool CheckForSecurityRights(SecurityRights action, SolicitudesEstadosList ObjectListOrEntityList)
        //{
        //    switch (action)
        //    {
        //        case SecurityRights.Read:
        //            return true;
        //        case SecurityRights.Insert:
        //            return true;
        //        case SecurityRights.Update:
        //            return true;
        //        case SecurityRights.Delete:
        //            return true;
        //    }
        //    return false;
        //}

    }

}


namespace serin_viaticosRules.Loaders
{

    /// <summary>
    /// Loader for SolicitudesEstados entity
    /// This class provide get methods for this entity
    /// </summary>
    public partial class SolicitudesEstadosLoader
    {
    }

}



