
        
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// You can edit this file as your wish.
//------------------------------------------------------------------------------

using System;
using Cooperator.Framework.Data;
using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using serin_viaticosRules.Entities;


using serin_viaticosRules.Objects;


using serin_viaticosRules.Gateways;


using serin_viaticosRules.Mappers;


using System.Collections.Generic;

namespace serin_viaticosRules.LazyProviders
{
    /// <summary>
    /// 
    /// </summary>
    public class DefaultLazyProvider: ILazyProvider
    {
        private static Object thisLock = new Object();
        private static Dictionary<string, IGenericGateway> _mappersCache;
        private static Dictionary<string, IGenericGateway> MappersCache
        {
            get
            {
                lock (thisLock)
                {
                    if (DefaultLazyProvider._mappersCache == null)
                    {
                        DefaultLazyProvider._mappersCache = new Dictionary<string, IGenericGateway>();
                        
                        DefaultLazyProvider._mappersCache.Add("serin_viaticosRules.Entities.CategoriasGasto", serin_viaticosRules.Mappers.CategoriasGastoMapper.Instance());
                        
                        DefaultLazyProvider._mappersCache.Add("serin_viaticosRules.Objects.CategoriasGastoObject", serin_viaticosRules.Gateways.CategoriasGastoGateway.Instance());
                    
                        DefaultLazyProvider._mappersCache.Add("serin_viaticosRules.Entities.Perfiles", serin_viaticosRules.Mappers.PerfilesMapper.Instance());
                        
                        DefaultLazyProvider._mappersCache.Add("serin_viaticosRules.Objects.PerfilesObject", serin_viaticosRules.Gateways.PerfilesGateway.Instance());
                    
                        DefaultLazyProvider._mappersCache.Add("serin_viaticosRules.Entities.PerfilesUsuarios", serin_viaticosRules.Mappers.PerfilesUsuariosMapper.Instance());
                        
                        DefaultLazyProvider._mappersCache.Add("serin_viaticosRules.Objects.PerfilesUsuariosObject", serin_viaticosRules.Gateways.PerfilesUsuariosGateway.Instance());
                    
                        DefaultLazyProvider._mappersCache.Add("serin_viaticosRules.Entities.UsuariosDependencia", serin_viaticosRules.Mappers.UsuariosDependenciaMapper.Instance());
                        
                        DefaultLazyProvider._mappersCache.Add("serin_viaticosRules.Objects.UsuariosDependenciaObject", serin_viaticosRules.Gateways.UsuariosDependenciaGateway.Instance());
                    
                    }
                }
                return DefaultLazyProvider._mappersCache;
            }
        }    


        /// <summary>
        /// Get associated entity for this entity
        /// </summary>
        public IUniqueIdentifiable GetEntity(System.Type child, IUniqueIdentifiable indentifier)
        {
            IGenericGateway genericGateway = DefaultLazyProvider.MappersCache[child.FullName];
            return genericGateway.GetOne(indentifier) as IUniqueIdentifiable;
        }

        /// <summary>
        /// Get collection based in the parent entity
        /// </summary>
        public object GetList(System.Type child, IUniqueIdentifiable parent)
        {
            IGenericGateway genericGateway = DefaultLazyProvider.MappersCache[child.FullName];
            return genericGateway.GetByParent(parent);
        }
    }
}


